<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE AuditEvent PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<AuditEvent action="ProvisioningFailure" interface="LCM" serverHost="WIN-T21N4E0UF24" source="Scheduler" target="ISIN1003">
  <Attributes>
    <Map>
      <entry key="error1" value="Connection timed out: connect"/>
      <entry key="error2" value="Exception occurred while executing the RPCRequest: Errors returned from IQService. &quot;The object already exists. 00000524: UpdErr: DSID-031A11C4, problem 6005 (ENTRY_EXISTS), data 0 . HRESULT:[0x80071392] For identity: CN=Claire.Divas,OU=Test,DC=ENH,DC=local&quot;"/>
      <entry key="taskResultId" value="0a00030f8d871ab7818d8789e48900cb"/>
    </Map>
  </Attributes>
  <String1>FailedApplications=Active Directory</String1>
</AuditEvent>